spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    platform: Mysql

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jakcy.examples.mybatis.generator.pojo